# Generated by Django 2.2.7 on 2019-11-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTitle', models.CharField(help_text='店名', max_length=20)),
                ('cAddr', models.CharField(default='', help_text='地址', max_length=255)),
                ('cCate', models.CharField(default='', help_text='類別(飯、麵)', max_length=255)),
                ('cLatitude', models.CharField(blank=True, default='', help_text='經度', max_length=255)),
                ('cLongitude', models.CharField(blank=True, default='', help_text='緯度', max_length=255)),
                ('cName', models.CharField(help_text='推薦人', max_length=20)),
            ],
        ),
    ]
